Check for absolute directories in configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -36,8 +36,8 @@ Compilation variables:
     LDFLAGS            Linker flags (-L<dir> ...)
     LIBS               Libraries (-l<library> ...)
 
-    SDL_CFLAGS        Additional flags for compiling with SDL2
-    SDL_LIBS          Additional flags for linking with SDL2
+    SDL_CFLAGS         Additional flags for compiling with SDL2
+    SDL_LIBS           Additional flags for linking with SDL2
 EOF
 }
 
@@ -73,7 +73,7 @@ set_othervars=no
 # Command-line parsing
 # --------------------
 # To keep things simple we require that options with parameters use the
-# --key=value notation. Please don't use --key value, whithout the "=".
+# --key=value notation. Please don't use --key value, without the "=".
 
 nl='
 '
@@ -100,7 +100,7 @@ for arg in "$@"; do
             ;;
 
         -*)
-            echo >&2 "Unrecognized option $arg"
+            echo >&2 "ERROR: Unrecognized option $arg"
             exit 1
             ;;
 
@@ -117,6 +117,35 @@ for arg in "$@"; do
         *=*)
             othervars="${othervars}${key} = ${value}${nl}"
             set_othervars=yes
+            ;;
+    esac
+done
+
+# Check for absolute directories
+# ------------------------------
+# The installation directories will be hardcoded into the executable so it is
+# important that they be absolute directories. We also forbid any paths that
+# start with a "~". They can be problematic because shell tilde expansion only
+# happens if the tilde is at the start of the word. The end result is that
+# the tilde is expanded when we present the installation paths to the user but
+# it does not always get expanded when those paths are used in the Makefile.
+
+for varname in prefix bindir datadir; do
+    eval "value=\$$varname"
+    case "$value" in
+        /*)
+            # Is am absolute path
+            ;;
+        \$*)
+            # Assume that variable expansions will become an absolute path
+            ;;
+        \~*)
+            echo >&2 "ERROR: Please write \$HOME instead of ~ for the $varname."
+            exit 1
+            ;;
+        *)
+            echo >&2 "ERROR: Please specify an absolute directory for the $varname."
+            exit 1
             ;;
     esac
 done
