Clarify an error message

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -127,8 +127,8 @@ done
 # important that they be absolute directories. We also forbid any paths that
 # start with a "~". They can be problematic because shell tilde expansion only
 # happens if the tilde is at the start of the word. The end result is that
-# the tilde is expanded when we present the installation paths to the user but
-# it does not always get expanded when those paths are used in other places.
+# the tilde would be expanded when we present the installation paths to the
+# user but it not when those paths are used in other places.
 
 for varname in prefix bindir datadir; do
     eval "value=\$$varname"
@@ -137,14 +137,15 @@ for varname in prefix bindir datadir; do
             # Is am absolute path
             ;;
         \$*)
-            # Assume that variable expansions will become an absolute path
+            # Is a variable reference
+            # Assume that it expand into an absolute path
             ;;
         \~*)
             echo >&2 "ERROR: Please write \$HOME instead of ~ for the --$varname."
             exit 1
             ;;
         *)
-            echo >&2 "ERROR: Please specify an absolute path for the --$varname."
+            echo >&2 "ERROR: Please specify an absolute path for --$varname. $value is not an absolute path."
             exit 1
             ;;
     esac
